@startuml
!theme hacker

left to right direction
actor "Visitor" as visitor
actor "User" as user
actor "Admin" as admin
rectangle MyApp {
  usecase "Create account" as UC1
  usecase "Log in" as UC2
  usecase "Consult games list" as UC5
  usecase "Consult heroes list" as UC6
  usecase "Create game card" as UC7
  usecase "Create hero card" as UC8

  usecase "Manage users" as UC10
  usecase "Manage games & heroes cards" as UC11
  usecase "Manage reviews" as UC12
}
visitor <|- user
visitor --> UC1
visitor --> UC5
visitor --> UC6
user ---> UC7
user ---> UC8
UC2 ..> UC5
UC2 ..> UC6
UC5 <-- admin
UC6 <-- admin
UC7 <-- admin
UC8 <-- admin
UC10 <-- admin
UC11 <-- admin
UC12 <-- admin
@enduml